apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-parksmap
  namespace: myargocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: app-parksmap
  source:
    directory:
      recurse: true
    path: app-parksmap
    repoURL: https://github.com/cbowland/openshift-gitops-getting-started.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
